export const movies = [
    {name:'amelie', status:'unrevealed', path:require('./../assets/images/amelie.jpg').default},
    {name:'back_to_the_future', status:'unrevealed', path:require('./../assets/images/back_to_the_future.jpg').default},
    {name:'paris_is_burning', status:'unrevealed', path:require('./../assets/images/parris_is_burning.jpg').default},
    {name:'pulp_fiction', status:'unrevealed', path:require('./../assets/images/pulp_fiction.jpg').default},
    {name:'reservior_dogs', status:'unrevealed', path:require('./../assets/images/reservior_dogs.jpg').default},
    {name:'terminator', status:'unrevealed', path:require('./../assets/images/terminator.jpg').default},
    {name:'aladdin', status:'unrevealed', path:require('./../assets/images/aladdin.jpg').default},
    {name:'dirty_dancing', status:'unrevealed', path:require('./../assets/images/dirty_dancing.jpg').default},
    {name:'nightmare_elem_street', status:'unrevealed', path:require('./../assets/images/nightmare_elem_street.jpg').default},
    {name:'big', status:'unrevealed', path:require('./../assets/images/big.jpg').default},
    {name:'mission_impossible', status:'unrevealed', path:require('./../assets/images/mission_impossible.jpg').default},
    {name:'indiana_jones', status:'unrevealed', path:require('./../assets/images/indiana_jones.jpeg').default},
    {name:'fight_club', status:'unrevealed', path:require('./../assets/images/fight_club.jpg').default},
    {name:'the_shining', status:'unrevealed', path:require('./../assets/images/the_shining.jpg').default},
    {name:'scream', status:'unrevealed', path:require('./../assets/images/scream.jpg').default},
    {name:'home_alone', status:'unrevealed', path:require('./../assets/images/home_alone.jpg').default},
    {name:'matrix', status:'unrevealed', path:require('./../assets/images/matrix.jpg').default},
    {name:'lambs_silience', status:'unrevealed', path:require('./../assets/images/lambs_silience.jpg').default},
]